### ISSUE TITLE
hf array depends on the length of the data

### ISSUE THREAD

**Issue by arnodelorme** [amisepa/BrainBeats#20]
size 4 x 1 for 120 seconds and size 11 x 1 for 300 seconds

**Comment by arnodelorme** [comment]
Also lf does not show up for the short data

**Comment by amisepa** [comment]
Yes I check if minimum length is provided by data and only export outputs accordingly, so that users don't export unreliable HRV measures. See the Schaffer and Ginsberg paper. 
For example, you can't get reliable ULF with less than 24 hours of data

**Comment by arnodelorme** [comment]
Yes, it is based on the number of segments. It is OK.
