### ISSUE TITLE
cannot run tutorial with message "Unrecognized function or variable 'flaggedRatio'."

### ISSUE THREAD

**Issue by npdrbong** [amisepa/BrainBeats#23]
I am running tutorial with bioRxiv pdf file.
https://www.biorxiv.org/content/10.1101/2023.06.01.543272v1.full.pdf

to do this, I installed v1.0 from this github but error message popped.

Do you have any solution about this issue?

![image](https://github.com/amisepa/BrainBeats/assets/102932662/d62e6f06-cf42-4e6b-b9df-5c0ae6b4952d)

**Comment by amisepa** [comment]
Sorry about this issue. I think this one is only if you run the version installed via EEGLAB, I need to make a new release. The GitHub version works for me. 
Are you sure you didn't install brainbeats via eeglab? Try deleting any brainbeats folder in eeglab > plugins and close/unzip the repo again. 
Let me know if that works.

**Comment by npdrbong** [comment]
Thank you a lot! Problem solved.
