### ISSUE TITLE
"EEGLAB error in function get_eeg_features() at line 203:"

### ISSUE THREAD

**Issue by evgeorgaras** [amisepa/BrainBeats#29]
Hello and thank you for this - very useful - plugin 

I' ve been trying to analyze a number of datasets and have been encountering the same error in each one that I have tested.

I'm using Matlab R2023a, latest version of EEGLAB and latest version of BrainBeats from github.

My datasets have 32 EEG channels + 1 ECG, and a duration of ~500sec, are referenced to average and have channel locations.

I'm using the mode "Extract EEG and HRV features" and the error occurs specifically when extracting EEG frequency domain features.

The following happens for all EEG channels, although not for the same frequency bands. 

![image](https://github.com/amisepa/BrainBeats/assets/151952146/1ed6145a-9862-46b0-bc80-34b132535dae)

After not being able to detect individualized frequency bounds: 

![image](https://github.com/amisepa/BrainBeats/assets/151952146/767ea798-c822-4b27-a46a-efbff1968686)

and then this error window appears:

![image](https://github.com/amisepa/BrainBeats/assets/151952146/0bba0656-4530-4f56-87a6-620e109c0bf5)

I will appreciate any help as I have no clue about what could be causing this error or how to solve it
Thank you for your time!

**Comment by amisepa** [comment]
I fixed the error. Please make a pull or download the v1.4. available here on Github, try again, and let me know if works for you. I made. I made a lot of other fixes and improvements over the past 2 weeks. Let me know if you get other problems. 

Thanks!
Cedric
