### ISSUE TITLE
Infinity reference error

### ISSUE THREAD

**Issue by MariusKlug** [amisepa/BrainBeats#32]
When running the first HEP method on the tutorial dataset using defaults I receive this error:

![image](https://github.com/amisepa/BrainBeats/assets/1765664/92476a56-2578-43c6-945d-6d9134d92fd0)

I have the REST1.2 toolbox installed, which did not fix the issue. I could only proceed when switching to average reference.

I use MATLAB r2023a and EEGLAB2023.1

**Comment by amisepa** [comment]
Hi Marius,
Thanks for pointing it out. That's because REST1.2 is the original GUI version and you need to the REST_cmd plugin (command line version). I'll add a fix now.

**Comment by amisepa** [comment]
Strange. It should have been installed automatically by run_checks.m line 112

Can you type this in your command window and see if installs it successfully?
`plugin_askinstall('REST_cmd', 'REST_cmd', 1);`

**Comment by amisepa** [comment]
I don't get this error after uninstalling REST plugins. Did you run it via GUI or command line?

**Comment by amisepa** [comment]
I put Infomax as the default ICA method to avoid this potential issue. 

Thanks Marius!
