### ISSUE TITLE
Tutorial error Method 1

### ISSUE THREAD

**Issue by MariusKlug** [amisepa/BrainBeats#33]
When running the tutorial I get this error:

![image](https://github.com/amisepa/BrainBeats/assets/1765664/65d3cd1f-3575-4ba5-abb9-a0f1ce9233be)

Also on MATLAB r2023a and EEGLAB2023.1.

**Comment by amisepa** [comment]
Added a fix. Not sure why this wasn't detected before. Can you do a pull of BrainBeats and try again?
