### ISSUE TITLE
Cannot run alpha asymetry without Heart channel

### ISSUE THREAD

**Issue by arnodelorme** [amisepa/BrainBeats#37]
I tried again for 20 minutes not using my modified functions. Did not work.

**Comment by amisepa** [comment]
Faut que je mette à jour avec tes changements oui dsl. Utilise get_eeg_features() en attendant avec les quelques paramètres que je t’avais envoyé par mail

**Comment by arnodelorme** [comment]
OK

**Comment by amisepa** [comment]
resolved, see brainbeats_tutorial for command (at the bottom of the script)
