### ISSUE TITLE
Running the tutorial 

### ISSUE THREAD

**Issue by arnodelorme** [amisepa/BrainBeats#39]
On the main branch, with the latest changes as of today.
started "brainbeats_tutorial"

This question poped up.

![Screenshot 2024-03-08 at 12 27 32 PM](https://github.com/amisepa/BrainBeats/assets/1872705/9ba072f3-0408-4f97-ae7f-fe837a89263c)

The first time, I answered no and got this error

![Screenshot 2024-03-08 at 12 27 47 PM](https://github.com/amisepa/BrainBeats/assets/1872705/305167c1-ed6c-4e1f-aed8-3843c0e7cc43)

The second time, I answered yes, and got this error

![Screenshot 2024-03-08 at 12 28 07 PM](https://github.com/amisepa/BrainBeats/assets/1872705/cdcf161c-2430-4d84-8519-2351c835cafa)

**Comment by amisepa** [comment]
> This question poped up.
You have to click Yes. 

Can you pull the v1.4 branch and try again?

**Comment by arnodelorme** [comment]
Yes, it works with v1.4. However, you should develop in the branch “develop” and “main” should be your last release (v1.4). You do not need a branch v1.4 only a tag 1.4 on the main branch.

**Comment by amisepa** [comment]
ok, I'll do that, thanks!
