### ISSUE TITLE
Other missing function

### ISSUE THREAD

**Issue by arnodelorme** [amisepa/BrainBeats#4]
At this point most users have given up. Testing is part of developing, make a second clone to check that it works.

![Screen Shot 2023-05-09 at 11 10 51 AM](https://github.com/amisepa/BrainBeats/assets/1872705/62b842d2-8a2d-4112-bf94-765ec8f83488)

**Comment by amisepa** [comment]
You're not most users you're helping me develop it. It won't be like this when it is released obviously.

The function is in the functions folder. Did you clone the repo in EEGLAB > plugins? 
If you put a break point in pop_BrainBeats line 10, does mainpath have the right path for you? This migh not be the best way to do it to add path to the functions folder.

mainpath = fileparts(which('pop_BrainBeats.m'));
addpath(fullfile(mainpath, 'functions'));

**Comment by amisepa** [comment]
That's why you're helping me make sure there is no errors left :)

it's fixed
