### ISSUE TITLE
"EEGLAB error in function gen_colormap() at line 402"

### ISSUE THREAD

**Issue by tysonperez** [amisepa/BrainBeats#42]
Hi, 
I am doing the "Extract EEG & HRV features" single-subject analysis tutorial.  Following the HRV analysis, I keep getting this error during the EEG analysis.

<img width="803" alt="Error_BrainBeats" src="https://github.com/amisepa/BrainBeats/assets/33464158/1a8b6aaa-3726-4d8a-a269-d3474979e793">

**Comment by amisepa** [comment]
I am not getting the error. Can you pull changes from eeglab (or re-install EEGLAB) and see if you still get the error?

**Comment by tysonperez** [comment]
Ok.  I currently have EEGLAB v2023.0.  I will install v2024.0 and see if it corrects the issue.

**Comment by tysonperez** [comment]
No luck.  I installed v2024.0 and still got the same error.  Could it be due to my parameter settings?  The only fields I changed were the "Power line noise (Hz)" to "50 Hz (Europe)" as well as enabling "Use GPU computing" & disabling "Use parallel computing".

![image](https://github.com/amisepa/BrainBeats/assets/33464158/b8bfdc46-0f4f-4dbf-8a09-d443d12fed5d)

**Comment by amisepa** [comment]
Mmh, no that's not it. The error is when plotting the raw EEG data with the removed channel and artifacts in red to see what has been removed. And the error is about the color of the events, which is very unnecessary... 

I made a potential fix, please re-install BrainBeats from the github repo (or pull if you use Git) and try again and let me know. 

Note that the GPU option does not really increase speed. This needs to be investigated and fixed. The parallel toolbox, however, can really increase speed for EEG features.

**Comment by tysonperez** [comment]
Just redownloaded & reinstalled BrainBeats from Github but same issue.  Can you think of anything else I can try?  If not, I will collect some EEG/ECG data later this week & try running my own file.

**Comment by amisepa** [comment]
I see, the input to turn off events is not taken into account when it should in vis_artifacts. 
Try this:
1) `open vis_artifacts `
2) comment these lines 143-150):
![image](https://github.com/amisepa/BrainBeats/assets/58382227/e9fe01da-bac0-4681-975e-e0b63c5de90c)

**Comment by tysonperez** [comment]
That worked!  Thank you!

**Comment by amisepa** [comment]
Yay! great to hear. Let me know if you have other questions or issues
