### ISSUE TITLE
Another one...

### ISSUE THREAD

**Issue by arnodelorme** [amisepa/BrainBeats#5]
![Screen Shot 2023-05-09 at 11 44 01 AM](https://github.com/amisepa/BrainBeats/assets/1872705/5ba53a7b-0a99-4a98-9e49-117dbf5a6fd3)

**Comment by amisepa** [comment]
haha. I need to submit release of the entropy plugin, and detect if it's not installed to ask to install it, like the eBiosig toolbox when you try to import a .bdf file for example.
But for now, I just added the functions here.

**Comment by arnodelorme** [comment]
Just copy the function to a private folder of BrainBeats

**Comment by amisepa** [comment]
what's a private folder? I copied it into the "functions" folder in BrainBeats

Cedric

------- Original Message -------
