### ISSUE TITLE
Fix data scroll for MAC or use another one

### ISSUE THREAD

**Issue by arnodelorme** [amisepa/BrainBeats#8]
It is important to be able to see the peaks and how they are detected

**Comment by amisepa** [comment]
I can't troubleshoot without a Mac

**Comment by amisepa** [comment]
I need to submit the paper we can fix that later

**Comment by amisepa** [comment]
I deleted the scrollplot functions by accident 2 weeks ago. Do you have the files on your computer?

**Comment by amisepa** [comment]
c'est bon j'ai trouve dans ta branche heureusement :)
